services:
    # antalaron_demo.service:
    #     class: 'Antalaron\Bundle\DemoBundle\Service'
    #     arguments: ['@dependency']
    #     tags:
    #         - { name: demo.tag, priority: 10 }

    antalaron_demo.default_controller:
        class: 'Antalaron\Bundle\DemoBundle\Controller\DefaultController'
