Antalaron\Bundle\DemoBundle\Model\Tag:
    repositoryClass: 'Antalaron\Bundle\DemoBundle\Repository\MongoDB\TagRepository'
    fields:
        id:
            id: true
        name:
            type: string
